In [93]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

In [94]:
df = pd.read_csv('adult.csv')

In [95]:
df.head()

   age workclass  fnlwgt  ... hours.per.week  native.country income
0   90         ?   77053  ...             40   United-States  <=50K
1   82   Private  132870  ...             18   United-States  <=50K
2   66         ?  186061  ...             40   United-States  <=50K
3   54   Private  140359  ...             40   United-States  <=50K
4   41   Private  264663  ...             40   United-States  <=50K

[5 rows x 15 columns]

In [96]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [97]:
df.shape

(32561, 15)

In [98]:
df.describe

<bound method NDFrame.describe of        age workclass  fnlwgt  ... hours.per.week  native.country income
0       90         ?   77053  ...             40   United-States  <=50K
1       82   Private  132870  ...             18   United-States  <=50K
2       66         ?  186061  ...             40   United-States  <=50K
3       54   Private  140359  ...             40   United-States  <=50K
4       41   Private  264663  ...             40   United-States  <=50K
...    ...       ...     ...  ...            ...             ...    ...
32556   22   Private  310152  ...             40   United-States  <=50K
32557   27   Private  257302  ...             38   United-States  <=50K
32558   40   Private  154374  ...             40   United-States   >50K
32559   58   Private  151910  ...             40   United-States  <=50K
32560   22   Private  201490  ...             20   United-States  <=50K

[32561 rows x 15 columns]>

In [99]:
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [100]:
df.duplicated().sum()

np.int64(24)

In [101]:
df[df.duplicated()]

       age         workclass  fnlwgt  ... hours.per.week  native.country income
8453    25           Private  308144  ...             40          Mexico  <=50K
8645    90           Private   52386  ...             35   United-States  <=50K
12202   21           Private  250051  ...             10   United-States  <=50K
14346   20           Private  107658  ...             10   United-States  <=50K
15603   25           Private  195994  ...             40       Guatemala  <=50K
17344   21           Private  243368  ...             50          Mexico  <=50K
19067   46           Private  173243  ...             40   United-States  <=50K
20388   30           Private  144593  ...             40               ?  <=50K
20507   19           Private   97261  ...             40   United-States  <=50K
22783   19           Private  138153  ...             10   United-States  <=50K
22934   19           Private  146679  ...             30   United-States  <=50K
23276   49           Private   31267  ...             40   United-States  <=50K
23660   25           Private  195994  ...             40       Guatemala  <=50K
23720   44           Private  367749  ...             45          Mexico  <=50K
23827   49  Self-emp-not-inc   43479  ...             40   United-States  <=50K
26738   23           Private  240137  ...             55          Mexico  <=50K
27133   28           Private  274679  ...             50   United-States  <=50K
28796   27           Private  255582  ...             40   United-States  <=50K
29051   42           Private  204235  ...             40   United-States   >50K
29334   39           Private   30916  ...             40   United-States  <=50K
29604   38           Private  207202  ...             48   United-States   >50K
31060   46           Private  133616  ...             40   United-States  <=50K
32065   19           Private  251579  ...             14   United-States  <=50K
32419   35           Private  379959  ...             40   United-States  <=50K

[24 rows x 15 columns]

In [102]:
df[df.duplicated(keep=False)]

       age         workclass  fnlwgt  ... hours.per.week  native.country income
6227    90           Private   52386  ...             35   United-States  <=50K
7615    19           Private  251579  ...             14   United-States  <=50K
7978    25           Private  308144  ...             40          Mexico  <=50K
8356    21           Private  250051  ...             10   United-States  <=50K
8453    25           Private  308144  ...             40          Mexico  <=50K
8500    38           Private  207202  ...             48   United-States   >50K
8645    90           Private   52386  ...             35   United-States  <=50K
9067    27           Private  255582  ...             40   United-States  <=50K
9269    20           Private  107658  ...             10   United-States  <=50K
9305    25           Private  195994  ...             40       Guatemala  <=50K
10307   19           Private  138153  ...             10   United-States  <=50K
10357   49  Self-emp-not-inc   43479  ...             40   United-States  <=50K
11121   49           Private   31267  ...             40   United-States  <=50K
11261   21           Private  243368  ...             50          Mexico  <=50K
11777   28           Private  274679  ...             50   United-States  <=50K
12202   21           Private  250051  ...             10   United-States  <=50K
13260   42           Private  204235  ...             40   United-States   >50K
14346   20           Private  107658  ...             10   United-States  <=50K
14634   46           Private  133616  ...             40   United-States  <=50K
15603   25           Private  195994  ...             40       Guatemala  <=50K
17344   21           Private  243368  ...             50          Mexico  <=50K
17456   19           Private  146679  ...             30   United-States  <=50K
18417   46           Private  173243  ...             40   United-States  <=50K
18906   35           Private  379959  ...             40   United-States  <=50K
19014   30           Private  144593  ...             40               ?  <=50K
19067   46           Private  173243  ...             40   United-States  <=50K
19622   19           Private   97261  ...             40   United-States  <=50K
19832   44           Private  367749  ...             45          Mexico  <=50K
20388   30           Private  144593  ...             40               ?  <=50K
20507   19           Private   97261  ...             40   United-States  <=50K
22595   23           Private  240137  ...             55          Mexico  <=50K
22783   19           Private  138153  ...             10   United-States  <=50K
22934   19           Private  146679  ...             30   United-States  <=50K
23276   49           Private   31267  ...             40   United-States  <=50K
23660   25           Private  195994  ...             40       Guatemala  <=50K
23720   44           Private  367749  ...             45          Mexico  <=50K
23827   49  Self-emp-not-inc   43479  ...             40   United-States  <=50K
26531   39           Private   30916  ...             40   United-States  <=50K
26738   23           Private  240137  ...             55          Mexico  <=50K
27133   28           Private  274679  ...             50   United-States  <=50K
28796   27           Private  255582  ...             40   United-States  <=50K
29051   42           Private  204235  ...             40   United-States   >50K
29334   39           Private   30916  ...             40   United-States  <=50K
29604   38           Private  207202  ...             48   United-States   >50K
31060   46           Private  133616  ...             40   United-States  <=50K
32065   19           Private  251579  ...             14   United-States  <=50K
32419   35           Private  379959  ...             40   United-States  <=50K

[47 rows x 15 columns]

In [103]:
df = df.drop_duplicates()

In [104]:
df.duplicated().sum()

np.int64(0)

In [105]:
df['workclass'].value_counts()

workclass
Private             22673
Self-emp-not-inc     2540
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [106]:
df['occupation'].value_counts()

occupation
Prof-specialty       4136
Craft-repair         4094
Exec-managerial      4065
Adm-clerical         3768
Sales                3650
Other-service        3291
Machine-op-inspct    2000
?                    1843
Transport-moving     1597
Handlers-cleaners    1369
Farming-fishing       992
Tech-support          927
Protective-serv       649
Priv-house-serv       147
Armed-Forces            9
Name: count, dtype: int64

In [107]:
df = df.replace('?',np.nan)

In [108]:
df

       age workclass  fnlwgt  ... hours.per.week  native.country income
0       90       NaN   77053  ...             40   United-States  <=50K
1       82   Private  132870  ...             18   United-States  <=50K
2       66       NaN  186061  ...             40   United-States  <=50K
3       54   Private  140359  ...             40   United-States  <=50K
4       41   Private  264663  ...             40   United-States  <=50K
...    ...       ...     ...  ...            ...             ...    ...
32556   22   Private  310152  ...             40   United-States  <=50K
32557   27   Private  257302  ...             38   United-States  <=50K
32558   40   Private  154374  ...             40   United-States   >50K
32559   58   Private  151910  ...             40   United-States  <=50K
32560   22   Private  201490  ...             20   United-States  <=50K

[32537 rows x 15 columns]

In [109]:
df.isna().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     582
income               0
dtype: int64

In [110]:
df.isna().sum().sum()

np.int64(4261)

In [111]:
df[df.isna().any(axis=1)].shape

(2398, 15)

In [112]:
df.isna().any(axis=1).sum()

np.int64(2398)

In [113]:
df.shape

(32537, 15)

In [115]:
# df = df.dropna()
df.dropna(inplace = True)

In [116]:
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30139 entries, 1 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30139 non-null  int64
 1   workclass       30139 non-null  object
 2   fnlwgt          30139 non-null  int64
 3   education       30139 non-null  object
 4   education.num   30139 non-null  int64
 5   marital.status  30139 non-null  object
 6   occupation      30139 non-null  object
 7   relationship    30139 non-null  object
 8   race            30139 non-null  object
 9   sex             30139 non-null  object
 10  capital.gain    30139 non-null  int64
 11  capital.loss    30139 non-null  int64
 12  hours.per.week  30139 non-null  int64
 13  native.country  30139 non-null  object
 14  income          30139 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [120]:
df.describe()

                age        fnlwgt  ...  capital.loss  hours.per.week
count  30139.000000  3.013900e+04  ...  30139.000000    30139.000000
mean      38.441720  1.897950e+05  ...     88.439928       40.934703
std       13.131426  1.056586e+05  ...    404.445239       11.978753
min       17.000000  1.376900e+04  ...      0.000000        1.000000
25%       28.000000  1.176275e+05  ...      0.000000       40.000000
50%       37.000000  1.784170e+05  ...      0.000000       40.000000
75%       47.000000  2.376045e+05  ...      0.000000       45.000000
max       90.000000  1.484705e+06  ...   4356.000000       99.000000

[8 rows x 6 columns]

In [122]:
df.describe(include = 'object')

       workclass education      marital.status  ...    sex native.country income
count      30139     30139               30139  ...  30139          30139  30139
unique         7        16                   7  ...      2             41      2
top      Private   HS-grad  Married-civ-spouse  ...   Male  United-States  <=50K
freq       22264      9834               14059  ...  20366          27487  22633

[4 rows x 9 columns]