In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

In [4]:
df = pd.read_csv('adult.csv')

In [5]:
df.head()

   age workclass  fnlwgt  ... hours.per.week  native.country income
0   90         ?   77053  ...             40   United-States  <=50K
1   82   Private  132870  ...             18   United-States  <=50K
2   66         ?  186061  ...             40   United-States  <=50K
3   54   Private  140359  ...             40   United-States  <=50K
4   41   Private  264663  ...             40   United-States  <=50K

[5 rows x 15 columns]

In [6]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

In [8]:
df.shape

(32561, 15)

In [11]:
df.describe

<bound method NDFrame.describe of        age workclass  fnlwgt  ... hours.per.week  native.country income
0       90         ?   77053  ...             40   United-States  <=50K
1       82   Private  132870  ...             18   United-States  <=50K
2       66         ?  186061  ...             40   United-States  <=50K
3       54   Private  140359  ...             40   United-States  <=50K
4       41   Private  264663  ...             40   United-States  <=50K
...    ...       ...     ...  ...            ...             ...    ...
32556   22   Private  310152  ...             40   United-States  <=50K
32557   27   Private  257302  ...             38   United-States  <=50K
32558   40   Private  154374  ...             40   United-States   >50K
32559   58   Private  151910  ...             40   United-States  <=50K
32560   22   Private  201490  ...             20   United-States  <=50K

[32561 rows x 15 columns]>

In [12]:
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(24)

In [15]:
df[df.duplicated()]

       age         workclass  fnlwgt  ... hours.per.week  native.country income
8453    25           Private  308144  ...             40          Mexico  <=50K
8645    90           Private   52386  ...             35   United-States  <=50K
12202   21           Private  250051  ...             10   United-States  <=50K
14346   20           Private  107658  ...             10   United-States  <=50K
15603   25           Private  195994  ...             40       Guatemala  <=50K
17344   21           Private  243368  ...             50          Mexico  <=50K
19067   46           Private  173243  ...             40   United-States  <=50K
20388   30           Private  144593  ...             40               ?  <=50K
20507   19           Private   97261  ...             40   United-States  <=50K
22783   19           Private  138153  ...             10   United-States  <=50K
22934   19           Private  146679  ...             30   United-States  <=50K
23276   49           Private   31267  ...             40   United-States  <=50K
23660   25           Private  195994  ...             40       Guatemala  <=50K
23720   44           Private  367749  ...             45          Mexico  <=50K
23827   49  Self-emp-not-inc   43479  ...             40   United-States  <=50K
26738   23           Private  240137  ...             55          Mexico  <=50K
27133   28           Private  274679  ...             50   United-States  <=50K
28796   27           Private  255582  ...             40   United-States  <=50K
29051   42           Private  204235  ...             40   United-States   >50K
29334   39           Private   30916  ...             40   United-States  <=50K
29604   38           Private  207202  ...             48   United-States   >50K
31060   46           Private  133616  ...             40   United-States  <=50K
32065   19           Private  251579  ...             14   United-States  <=50K
32419   35           Private  379959  ...             40   United-States  <=50K

[24 rows x 15 columns]

In [16]:
df[df.duplicated(keep=False)]

       age         workclass  fnlwgt  ... hours.per.week  native.country income
6227    90           Private   52386  ...             35   United-States  <=50K
7615    19           Private  251579  ...             14   United-States  <=50K
7978    25           Private  308144  ...             40          Mexico  <=50K
8356    21           Private  250051  ...             10   United-States  <=50K
8453    25           Private  308144  ...             40          Mexico  <=50K
8500    38           Private  207202  ...             48   United-States   >50K
8645    90           Private   52386  ...             35   United-States  <=50K
9067    27           Private  255582  ...             40   United-States  <=50K
9269    20           Private  107658  ...             10   United-States  <=50K
9305    25           Private  195994  ...             40       Guatemala  <=50K
10307   19           Private  138153  ...             10   United-States  <=50K
10357   49  Self-emp-not-inc   43479  ...             40   United-States  <=50K
11121   49           Private   31267  ...             40   United-States  <=50K
11261   21           Private  243368  ...             50          Mexico  <=50K
11777   28           Private  274679  ...             50   United-States  <=50K
12202   21           Private  250051  ...             10   United-States  <=50K
13260   42           Private  204235  ...             40   United-States   >50K
14346   20           Private  107658  ...             10   United-States  <=50K
14634   46           Private  133616  ...             40   United-States  <=50K
15603   25           Private  195994  ...             40       Guatemala  <=50K
17344   21           Private  243368  ...             50          Mexico  <=50K
17456   19           Private  146679  ...             30   United-States  <=50K
18417   46           Private  173243  ...             40   United-States  <=50K
18906   35           Private  379959  ...             40   United-States  <=50K
19014   30           Private  144593  ...             40               ?  <=50K
19067   46           Private  173243  ...             40   United-States  <=50K
19622   19           Private   97261  ...             40   United-States  <=50K
19832   44           Private  367749  ...             45          Mexico  <=50K
20388   30           Private  144593  ...             40               ?  <=50K
20507   19           Private   97261  ...             40   United-States  <=50K
22595   23           Private  240137  ...             55          Mexico  <=50K
22783   19           Private  138153  ...             10   United-States  <=50K
22934   19           Private  146679  ...             30   United-States  <=50K
23276   49           Private   31267  ...             40   United-States  <=50K
23660   25           Private  195994  ...             40       Guatemala  <=50K
23720   44           Private  367749  ...             45          Mexico  <=50K
23827   49  Self-emp-not-inc   43479  ...             40   United-States  <=50K
26531   39           Private   30916  ...             40   United-States  <=50K
26738   23           Private  240137  ...             55          Mexico  <=50K
27133   28           Private  274679  ...             50   United-States  <=50K
28796   27           Private  255582  ...             40   United-States  <=50K
29051   42           Private  204235  ...             40   United-States   >50K
29334   39           Private   30916  ...             40   United-States  <=50K
29604   38           Private  207202  ...             48   United-States   >50K
31060   46           Private  133616  ...             40   United-States  <=50K
32065   19           Private  251579  ...             14   United-States  <=50K
32419   35           Private  379959  ...             40   United-States  <=50K

[47 rows x 15 columns]

In [17]:
df = df.drop_duplicates()

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df['workclass'].value_counts()

workclass
Private             22673
Self-emp-not-inc     2540
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [22]:
df['occupation'].value_counts()

occupation
Prof-specialty       4136
Craft-repair         4094
Exec-managerial      4065
Adm-clerical         3768
Sales                3650
Other-service        3291
Machine-op-inspct    2000
?                    1843
Transport-moving     1597
Handlers-cleaners    1369
Farming-fishing       992
Tech-support          927
Protective-serv       649
Priv-house-serv       147
Armed-Forces            9
Name: count, dtype: int64