In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv(r"C:\Users\chara\desktop\Machine_learning\Logistic_Regression\loan_data.csv")

In [3]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [4]:
x=df.drop(columns='loan_status')
y=df.loan_status

In [5]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,random_state=42,train_size=0.2)

In [6]:
obj_col=x.select_dtypes(include='string').columns

In [7]:
x[obj_col].nunique()

Series([], dtype: float64)

In [8]:
x['person_education'].unique()

array(['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate'],
      dtype=object)

In [9]:
order= ['High School','Associate','Bachelor','Master','Doctorate']

In [10]:
preprocessing=ColumnTransformer(
    transformers=[
        ('OneHotEncoder',OneHotEncoder(handle_unknown="ignore"),
                ['person_gender','person_home_ownership','loan_intent','previous_loan_defaults_on_file']),
        ('ordinal',OrdinalEncoder(categories=[order],handle_unknown='use_encoded_value',unknown_value=-1),
                ['person_education'])
    ],remainder="passthrough"
)

In [11]:
pipeline = Pipeline(
    steps=[("preprocessing",preprocessing),
          ('model',DecisionTreeClassifier(random_state=42))
          ]
        )

In [ ]:
grid_search_cv=GridSearchCV(
    estimator=pipeline,
    param_grid={
        'model__criterion':['gini','entropy'],
        'model__max_depth':[None,5,10],
        'model__min_samples_split':[2,5],
        'model__min_samples_leaf':[1,3],
        'model__splitter':['best','random']
    },
    verbose=10,
    n_jobs=-1 
)

In [23]:
grid_search_cv.fit(xtrain,ytrain)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

GridSearchCV(estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('OneHotEncoder',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['person_gender',
                                                                          'person_home_ownership',
                                                                          'loan_intent',
                                                                          'previous_loan_defaults_on_file']),
                                                                        ('ordinal',
                                                                         OrdinalEncoder(categories=[['High '
                                                                                                     'School',
                                                                                                     'Associate',
                                                                                                     'Bachelor',
                                                                                                     'Master',
                                                                                                     'Doctorate']],
                                                                                        handle_unknown='use_encoded_value',
                                                                                        unknown_value=-1),
                                                                         ['person_education'])])),
                                       ('model',
                                        DecisionTreeClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__criterion': ['gini', 'entropy'],
                         'model__max_depth': [None, 5, 10],
                         'model__min_samples_leaf': [1, 3],
                         'model__min_samples_split': [2, 5],
                         'model__splitter': ['best', 'random']},
             verbose=10)

In [14]:
grid_search_cv.best_estimator_ # It will return the best model/estimator

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('OneHotEncoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['person_gender',
                                                   'person_home_ownership',
                                                   'loan_intent',
                                                   'previous_loan_defaults_on_file']),
                                                 ('ordinal',
                                                  OrdinalEncoder(categories=[['High '
                                                                              'School',
                                                                              'Associate',
                                                                              'Bachelor',
                                                                              'Master',
                                                                              'Doctorate']],
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['person_education'])])),
                ('model',
                 DecisionTreeClassifier(max_depth=10, min_samples_leaf=3,
                                        random_state=42))])

In [15]:
grid_search_cv.best_params_ # it will return the best parameter values

{'model__criterion': 'gini',
 'model__max_depth': 10,
 'model__min_samples_leaf': 3,
 'model__min_samples_split': 2,
 'model__splitter': 'best'}

In [16]:
grid_search_cv.cv_results_

{'mean_fit_time': array([0.05357327, 0.02956514, 0.05426731, 0.02990522, 0.05295277,
        0.03192191, 0.05273137, 0.04025979, 0.03546958, 0.02164125,
        0.02883911, 0.01763306, 0.02915392, 0.01815553, 0.02505746,
        0.01647444, 0.03505435, 0.01927037, 0.03207183, 0.01832547,
        0.03248925, 0.01916118, 0.03535995, 0.01930552, 0.04703712,
        0.02328553, 0.04522271, 0.02314334, 0.04578085, 0.02083664,
        0.04964819, 0.02457776, 0.02925668, 0.01766787, 0.02773829,
        0.01755853, 0.02996397, 0.01691604, 0.02616405, 0.01660976,
        0.03645539, 0.01944208, 0.03561273, 0.018642  , 0.03532195,
        0.01914349, 0.04550333, 0.01883984]),
 'std_fit_time': array([0.00508031, 0.00026248, 0.00166842, 0.00063614, 0.00193289,
        0.0029887 , 0.00351672, 0.0040856 , 0.00358025, 0.00167338,
        0.00110456, 0.00054021, 0.00686043, 0.00133383, 0.00065849,
        0.00052688, 0.00320687, 0.00174117, 0.00057491, 0.00029472,
        0.00056735, 0.00060148, 0.0024937 , 0.0020057 , 0.00168985,
        0.00111617, 0.00115381, 0.00246262, 0.00397676, 0.00061434,
        0.00689965, 0.00343188, 0.00207983, 0.00079303, 0.00114575,
        0.00014376, 0.0013855 , 0.00045637, 0.00027399, 0.00034595,
        0.00077889, 0.00067466, 0.00022191, 0.00036023, 0.00059597,
        0.00092612, 0.01719871, 0.00024678]),
 'mean_score_time': array([0.00806255, 0.00795197, 0.00835276, 0.00824909, 0.00868955,
        0.00799694, 0.00965462, 0.01133022, 0.00799317, 0.00699539,
        0.00685434, 0.00594087, 0.00557098, 0.00659599, 0.0064034 ,
        0.00588446, 0.00696683, 0.00573006, 0.00588531, 0.00582314,
        0.00619025, 0.00585375, 0.00722122, 0.0056324 , 0.0065433 ,
        0.00610166, 0.0061811 , 0.00650377, 0.00700889, 0.00587149,
        0.00623503, 0.00658836, 0.00612288, 0.00660114, 0.00655508,
        0.00597558, 0.00666361, 0.00619674, 0.00657825, 0.00588999,
        0.00605555, 0.00617275, 0.00586758, 0.00589557, 0.00622511,
        0.00624585, 0.00600662, 0.0057795 ]),
 'std_score_time': array([0.00059357, 0.00064863, 0.00061094, 0.00043098, 0.00123106,
        0.00070757, 0.00323628, 0.00091304, 0.00068374, 0.0005185 ,
        0.00047447, 0.00045199, 0.00019823, 0.00132023, 0.00081289,
        0.00041273, 0.00071072, 0.00033542, 0.00029011, 0.000555  ,
        0.00073274, 0.00020773, 0.00116858, 0.00017462, 0.00160167,
        0.00052039, 0.00067122, 0.00055053, 0.00150725, 0.00019309,
        0.00081457, 0.00024897, 0.00046493, 0.00078572, 0.00038163,
        0.00057629, 0.00098231, 0.00040443, 0.00027983, 0.00033849,
        0.00053111, 0.00058077, 0.00029976, 0.00028029, 0.00043802,
        0.00070763, 0.00052867, 0.00012698]),
 'param_model__criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                    'gini', 'gini', 'gini', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                    'entropy', 'entropy'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_model__max_depth': masked_array(data=[None, None, None, None, None, None, None, None, 5, 5,
                    5, 5, 5, 5, 5, 5, 10, 10, 10, 10, 10, 10, 10, 10, None,
                    None, None, None, None, None, None, None, 5, 5, 5, 5,
                    5, 5, 5, 5, 10, 10, 10, 10, 10, 10, 10, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_model__min_samples_leaf': masked_array(data=[1, 1, 1, 1, 3, 3, 3, 3, 1, 1, 1, 1, 3, 3, 3, 3, 1, 1,
                    1, 1, 3, 3, 3, 3, 1, 1, 1, 1, 3, 3, 3, 3, 1, 1, 1, 1,
                    3, 3, 3, 3, 1, 1, 1, 1, 3, 3, 3, 3],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_model__min_samples_split': masked_array(data=[2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2,
                    5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5,
                    2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_model__splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'gini',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': None,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 5,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 2,
   'model__splitter': 'random'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'best'},
  {'model__criterion': 'entropy',
   'model__max_depth': 10,
   'model__min_samples_leaf': 3,
   'model__min_samples_split': 5,
   'model__splitter': 'random'}],
 'split0_test_score': array([0.88777778, 0.88055556, 0.89166667, 0.87222222, 0.89388889,
        0.88777778, 0.89388889, 0.88777778, 0.90722222, 0.84444444,
        0.90666667, 0.84444444, 0.90833333, 0.84444444, 0.90833333,
        0.84444444, 0.91111111, 0.90055556, 0.91388889, 0.89888889,
        0.915     , 0.88333333, 0.915     , 0.88333333, 0.88611111,
        0.87055556, 0.89611111, 0.87888889, 0.89222222, 0.88055556,
        0.89222222, 0.88055556, 0.90833333, 0.87777778, 0.90833333,
        0.87777778, 0.90888889, 0.87777778, 0.90888889, 0.87777778,
        0.90833333, 0.88055556, 0.90777778, 0.90166667, 0.90833333,
        0.89444444, 0.90833333, 0.89444444]),
 'split1_test_score': array([0.89111111, 0.88333333, 0.89111111, 0.90222222, 0.88666667,
        0.89      , 0.88666667, 0.89      , 0.90888889, 0.88166667,
        0.90888889, 0.88166667, 0.90888889, 0.88166667, 0.90888889,
        0.88166667, 0.91333333, 0.90777778, 0.91166667, 0.88555556,
        0.91333333, 0.89777778, 0.91333333, 0.89777778, 0.89333333,
        0.88222222, 0.88833333, 0.89277778, 0.88611111, 0.89111111,
        0.88611111, 0.89111111, 0.91      , 0.89111111, 0.91      ,
        0.89111111, 0.91      , 0.89111111, 0.91      , 0.89111111,
        0.91388889, 0.90222222, 0.91      , 0.89611111, 0.90944444,
        0.9       , 0.90944444, 0.9       ]),
 'split2_test_score': array([0.88444444, 0.86333333, 0.88833333, 0.87888889, 0.89055556,
        0.88555556, 0.89055556, 0.88555556, 0.91722222, 0.87666667,
        0.91722222, 0.87666667, 0.91722222, 0.87666667, 0.91722222,
        0.87666667, 0.91388889, 0.89277778, 0.91444444, 0.89166667,
        0.91666667, 0.90222222, 0.91666667, 0.90222222, 0.89277778,
        0.87777778, 0.88944444, 0.87777778, 0.89166667, 0.87777778,
        0.89166667, 0.87777778, 0.91444444, 0.87666667, 0.91444444,
        0.87666667, 0.91444444, 0.87666667, 0.91444444, 0.87666667,
        0.91277778, 0.88555556, 0.91166667, 0.89444444, 0.91555556,
        0.89166667, 0.91555556, 0.89166667]),
 'split3_test_score': array([0.89833333, 0.885     , 0.905     , 0.88722222, 0.90222222,
        0.90444444, 0.90222222, 0.90444444, 0.91833333, 0.9       ,
        0.91833333, 0.9       , 0.91888889, 0.9       , 0.91888889,
        0.9       , 0.92166667, 0.90444444, 0.92222222, 0.90888889,
        0.92055556, 0.90444444, 0.92055556, 0.90444444, 0.90222222,
        0.89277778, 0.90222222, 0.89166667, 0.895     , 0.895     ,
        0.895     , 0.895     , 0.91888889, 0.9       , 0.91888889,
        0.9       , 0.91888889, 0.9       , 0.91888889, 0.9       ,
        0.92277778, 0.91888889, 0.92333333, 0.89777778, 0.92166667,
        0.89222222, 0.92166667, 0.89222222]),
 'split4_test_score': array([0.87388889, 0.87      , 0.88166667, 0.88333333, 0.88944444,
        0.89277778, 0.88944444, 0.89277778, 0.91222222, 0.87388889,
        0.91222222, 0.87388889, 0.91222222, 0.87388889, 0.91222222,
        0.87388889, 0.91055556, 0.89944444, 0.90944444, 0.90277778,
        0.90666667, 0.89555556, 0.90666667, 0.89555556, 0.89111111,
        0.88777778, 0.89777778, 0.89055556, 0.89666667, 0.88611111,
        0.89666667, 0.88611111, 0.905     , 0.87388889, 0.905     ,
        0.87388889, 0.905     , 0.87388889, 0.905     , 0.87388889,
        0.91333333, 0.89555556, 0.91277778, 0.9       , 0.91277778,
        0.89222222, 0.91277778, 0.89222222]),
 'mean_test_score': array([0.88711111, 0.87644444, 0.89155556, 0.88477778, 0.89255556,
        0.89211111, 0.89255556, 0.89211111, 0.91277778, 0.87533333,
        0.91266667, 0.87533333, 0.91311111, 0.87533333, 0.91311111,
        0.87533333, 0.91411111, 0.901     , 0.91433333, 0.89755556,
        0.91444444, 0.89666667, 0.91444444, 0.89666667, 0.89311111,
        0.88222222, 0.89477778, 0.88633333, 0.89233333, 0.88611111,
        0.89233333, 0.88611111, 0.91133333, 0.88388889, 0.91133333,
        0.88388889, 0.91144444, 0.88388889, 0.91144444, 0.88388889,
        0.91422222, 0.89655556, 0.91311111, 0.898     , 0.91355556,
        0.89411111, 0.91355556, 0.89411111]),
 'std_test_score': array([0.00805383, 0.0083784 , 0.00760442, 0.0100468 , 0.00535874,
        0.00661461, 0.00535874, 0.00661461, 0.00440258, 0.01792508,
        0.00454606, 0.01792508, 0.00428319, 0.01792508, 0.00428319,
        0.01792508, 0.00398454, 0.00506013, 0.00432335, 0.00819967,
        0.00456773, 0.00737028, 0.00456773, 0.00737028, 0.00521867,
        0.00772202, 0.00521867, 0.00657905, 0.00360726, 0.00639251,
        0.00360726, 0.00639251, 0.00485086, 0.01001234, 0.00485086,
        0.01001234, 0.00478681, 0.01001234, 0.00478681, 0.01001234,
        0.0047088 , 0.0134825 , 0.00538172, 0.00259629, 0.00478681,
        0.0030952 , 0.00478681, 0.0030952 ]),
 'rank_test_score': array([34, 44, 33, 38, 27, 31, 27, 31, 11, 45, 12, 45,  8, 45,  8, 45,  5,
        17,  3, 19,  1, 20,  1, 20, 26, 43, 23, 35, 29, 36, 29, 36, 15, 39,
        15, 39, 13, 39, 13, 39,  4, 22,  8, 18,  6, 24,  6, 24],
       dtype=int32)}

In [17]:
results = pd.DataFrame(grid_search_cv.cv_results_)

In [18]:
# results

In [19]:
results.sort_values(by='rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__criterion,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
20,0.032489,0.000567,0.006190,0.000733,gini,10,3,2,best,"{'model__criterion': 'gini', 'model__max_depth...",0.915000,0.913333,0.916667,0.920556,0.906667,0.914444,0.004568,1
22,0.035360,0.002494,0.007221,0.001169,gini,10,3,5,best,"{'model__criterion': 'gini', 'model__max_depth...",0.915000,0.913333,0.916667,0.920556,0.906667,0.914444,0.004568,1
18,0.032072,0.000575,0.005885,0.000290,gini,10,1,5,best,"{'model__criterion': 'gini', 'model__max_depth...",0.913889,0.911667,0.914444,0.922222,0.909444,0.914333,0.004323,3
40,0.036455,0.000779,0.006056,0.000531,entropy,10,1,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.908333,0.913889,0.912778,0.922778,0.913333,0.914222,0.004709,4
16,0.035054,0.003207,0.006967,0.000711,gini,10,1,2,best,"{'model__criterion': 'gini', 'model__max_depth...",0.911111,0.913333,0.913889,0.921667,0.910556,0.914111,0.003985,5
44,0.035322,0.000596,0.006225,0.000438,entropy,10,3,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.908333,0.909444,0.915556,0.921667,0.912778,0.913556,0.004787,6
46,0.045503,0.017199,0.006007,0.000529,entropy,10,3,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.908333,0.909444,0.915556,0.921667,0.912778,0.913556,0.004787,6
12,0.029154,0.006860,0.005571,0.000198,gini,5,3,2,best,"{'model__criterion': 'gini', 'model__max_depth...",0.908333,0.908889,0.917222,0.918889,0.912222,0.913111,0.004283,8
42,0.035613,0.000222,0.005868,0.000300,entropy,10,1,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.907778,0.910000,0.911667,0.923333,0.912778,0.913111,0.005382,8
14,0.025057,0.000658,0.006403,0.000813,gini,5,3,5,best,"{'model__criterion': 'gini', 'model__max_depth...",0.908333,0.908889,0.917222,0.918889,0.912222,0.913111,0.004283,8
8,0.035470,0.003580,0.007993,0.000684,gini,5,1,2,best,"{'model__criterion': 'gini', 'model__max_depth...",0.907222,0.908889,0.917222,0.918333,0.912222,0.912778,0.004403,11
10,0.028839,0.001105,0.006854,0.000474,gini,5,1,5,best,"{'model__criterion': 'gini', 'model__max_depth...",0.906667,0.908889,0.917222,0.918333,0.912222,0.912667,0.004546,12
36,0.029964,0.001385,0.006664,0.000982,entropy,5,3,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.908889,0.910000,0.914444,0.918889,0.905000,0.911444,0.004787,13
38,0.026164,0.000274,0.006578,0.000280,entropy,5,3,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.908889,0.910000,0.914444,0.918889,0.905000,0.911444,0.004787,13
34,0.027738,0.001146,0.006555,0.000382,entropy,5,1,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.908333,0.910000,0.914444,0.918889,0.905000,0.911333,0.004851,15
32,0.029257,0.002080,0.006123,0.000465,entropy,5,1,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.908333,0.910000,0.914444,0.918889,0.905000,0.911333,0.004851,15
17,0.019270,0.001741,0.005730,0.000335,gini,10,1,2,random,"{'model__criterion': 'gini', 'model__max_depth...",0.900556,0.907778,0.892778,0.904444,0.899444,0.901000,0.005060,17
43,0.018642,0.000360,0.005896,0.000280,entropy,10,1,5,random,"{'model__criterion': 'entropy', 'model__max_de...",0.901667,0.896111,0.894444,0.897778,0.900000,0.898000,0.002596,18
19,0.018325,0.000295,0.005823,0.000555,gini,10,1,5,random,"{'model__criterion': 'gini', 'model__max_depth...",0.898889,0.885556,0.891667,0.908889,0.902778,0.897556,0.008200,19
23,0.019306,0.002006,0.005632,0.000175,gini,10,3,5,random,"{'model__criterion': 'gini', 'model__max_depth...",0.883333,0.897778,0.902222,0.904444,0.895556,0.896667,0.007370,20
21,0.019161,0.000601,0.005854,0.000208,gini,10,3,2,random,"{'model__criterion': 'gini', 'model__max_depth...",0.883333,0.897778,0.902222,0.904444,0.895556,0.896667,0.007370,20
41,0.019442,0.000675,0.006173,0.000581,entropy,10,1,2,random,"{'model__criterion': 'entropy', 'model__max_de...",0.880556,0.902222,0.885556,0.918889,0.895556,0.896556,0.013482,22
26,0.045223,0.001154,0.006181,0.000671,entropy,None,1,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.896111,0.888333,0.889444,0.902222,0.897778,0.894778,0.005219,23
45,0.019143,0.000926,0.006246,0.000708,entropy,10,3,2,random,"{'model__criterion': 'entropy', 'model__max_de...",0.894444,0.900000,0.891667,0.892222,0.892222,0.894111,0.003095,24
47,0.018840,0.000247,0.005780,0.000127,entropy,10,3,5,random,"{'model__criterion': 'entropy', 'model__max_de...",0.894444,0.900000,0.891667,0.892222,0.892222,0.894111,0.003095,24
24,0.047037,0.001690,0.006543,0.001602,entropy,None,1,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.886111,0.893333,0.892778,0.902222,0.891111,0.893111,0.005219,26
6,0.052731,0.003517,0.009655,0.003236,gini,None,3,5,best,"{'model__criterion': 'gini', 'model__max_depth...",0.893889,0.886667,0.890556,0.902222,0.889444,0.892556,0.005359,27
4,0.052953,0.001933,0.008690,0.001231,gini,None,3,2,best,"{'model__criterion': 'gini', 'model__max_depth...",0.893889,0.886667,0.890556,0.902222,0.889444,0.892556,0.005359,27
30,0.049648,0.006900,0.006235,0.000815,entropy,None,3,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.892222,0.886111,0.891667,0.895000,0.896667,0.892333,0.003607,29
28,0.045781,0.003977,0.007009,0.001507,entropy,None,3,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.892222,0.886111,0.891667,0.895000,0.896667,0.892333,0.003607,29
5,0.031922,0.002989,0.007997,0.000708,gini,None,3,2,random,"{'model__criterion': 'gini', 'model__max_depth...",0.887778,0.890000,0.885556,0.904444,0.892778,0.892111,0.006615,31
7,0.040260,0.004086,0.011330,0.000913,gini,None,3,5,random,"{'model__criterion': 'gini', 'model__max_depth...",0.887778,0.890000,0.885556,0.904444,0.892778,0.892111,0.006615,31
2,0.054267,0.001668,0.008353,0.000611,gini,None,1,5,best,"{'model__criterion': 'gini', 'model__max_depth...",0.891667,0.891111,0.888333,0.905000,0.881667,0.891556,0.007604,33
0,0.053573,0.005080,0.008063,0.000594,gini,None,1,2,best,"{'model__criterion': 'gini', 'model__max_depth...",0.887778,0.891111,0.884444,0.898333,0.873889,0.887111,0.008054,34
27,0.023143,0.002463,0.006504,0.000551,entropy,None,1,5,random,"{'model__criterion': 'entropy', 'model__max_de...",0.878889,0.892778,0.877778,0.891667,0.890556,0.886333,0.006579,35
29,0.020837,0.000614,0.005871,0.000193,entropy,None,3,2,random,"{'model__criterion': 'entropy', 'model__max_de...",0.880556,0.891111,0.877778,0.895000,0.886111,0.886111,0.006393,36
31,0.024578,0.003432,0.006588,0.000249,entropy,None,3,5,random,"{'model__criterion': 'entropy', 'model__max_de...",0.880556,0.891111,0.877778,0.895000,0.886111,0.886111,0.006393,36
3,0.029905,0.000636,0.008249,0.000431,gini,None,1,5,random,"{'model__criterion': 'gini', 'model__max_depth...",0.872222,0.902222,0.878889,0.887222,0.883333,0.884778,0.010047,38
39,0.016610,0.000346,0.005890,0.000338,entropy,5,3,5,random,"{'model__criterion': 'entropy', 'model__max_de...",0.877778,0.891111,0.876667,0.900000,0.873889,0.883889,0.010012,39
37,0.016916,0.000456,0.006197,0.000404,entropy,5,3,2,random,"{'model__criterion': 'entropy', 'model__max_de...",0.877778,0.891111,0.876667,0.900000,0.873889,0.883889,0.010012,39
33,0.017668,0.000793,0.006601,0.000786,entropy,5,1,2,random,"{'model__criterion': 'entropy', 'model__max_de...",0.877778,0.891111,0.876667,0.900000,0.873889,0.883889,0.010012,39
35,0.017559,0.000144,0.005976,0.000576,entropy,5,1,5,random,"{'model__criterion': 'entropy', 'model__max_de...",0.877778,0.891111,0.876667,0.900000,0.873889,0.883889,0.010012,39
25,0.023286,0.001116,0.006102,0.000520,entropy,None,1,2,random,"{'model__criterion': 'entropy', 'model__max_de...",0.870556,0.882222,0.877778,0.892778,0.887778,0.882222,0.007722,43
1,0.029565,0.000262,0.007952,0.000649,gini,None,1,2,random,"{'model__criterion': 'gini', 'model__max_depth...",0.880556,0.883333,0.863333,0.885000,0.870000,0.876444,0.008378,44
11,0.017633,0.000540,0.005941,0.000452,gini,5,1,5,random,"{'model__criterion': 'gini', 'model__max_depth...",0.844444,0.881667,0.876667,0.900000,0.873889,0.875333,0.017925,45
9,0.021641,0.001673,0.006995,0.000519,gini,5,1,2,random,"{'model__criterion': 'gini', 'model__max_depth...",0.844444,0.881667,0.876667,0.900000,0.873889,0.875333,0.017925,45
13,0.018156,0.001334,0.006596,0.001320,gini,5,3,2,random,"{'model__criterion': 'gini', 'model__max_depth...",0.844444,0.881667,0.876667,0.900000,0.873889,0.875333,0.017925,45
15,0.016474,0.000527,0.005884,0.000413,gini,5,3,5,random,"{'model__criterion': 'gini', 'model__max_depth...",0.844444,0.881667,0.876667,0.900000,0.873889,0.875333,0.017925,45

In [24]:
grid_search_cv.predict(xtrain)

array([1, 0, 0, ..., 0, 1, 0], shape=(9000,))