In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv(r"C:\Users\chara\desktop\Machine_learning\Logistic_Regression\loan_data.csv")

In [3]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [4]:
x=df.drop(columns='loan_status')
y=df.loan_status

In [5]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,random_state=42,train_size=0.2)

In [6]:
obj_col=x.select_dtypes(include='string').columns

In [7]:
x[obj_col].nunique()

Series([], dtype: float64)

In [8]:
x['person_education'].unique()

array(['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate'],
      dtype=object)

In [9]:
order= ['High School','Associate','Bachelor','Master','Doctorate']

In [10]:
preprocessing=ColumnTransformer(
    transformers=[
        ('OneHotEncoder',OneHotEncoder(handle_unknown="ignore"),
                ['person_gender','person_home_ownership','loan_intent','previous_loan_defaults_on_file']),
        ('ordinal',OrdinalEncoder(categories=[order],handle_unknown='use_encoded_value',unknown_value=-1),
                ['person_education'])
    ],remainder="passthrough"
)

In [11]:
pipeline = Pipeline(
    steps=[("preprocessing",preprocessing),
          ('model',RandomForestClassifier(random_state=42))
          ]
        )

In [18]:
grid_search_cv=GridSearchCV(
    estimator=pipeline,
    param_grid={
        'model__n_estimators':[100,200],
        'model__max_depth':[None,10,20],
        'model__min_samples_split':[2,5],
        'model__min_samples_leaf':[1,2],
        'model__max_features':['sqrt'],
        'model__class_weight':[None,'balanced']
    },
    verbose=10,
    n_jobs=-1 
)

In [19]:
grid_search_cv.fit(xtrain,ytrain)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

GridSearchCV(estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('OneHotEncoder',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['person_gender',
                                                                          'person_home_ownership',
                                                                          'loan_intent',
                                                                          'previous_loan_defaults_on_file']),
                                                                        ('ordinal',
                                                                         OrdinalEncoder(categories=[['High '
                                                                                                     'School',
                                                                                                     'Associate',
                                                                                                     'Bachelor',
                                                                                                     'Master',
                                                                                                     'Docto...
                                                                                        handle_unknown='use_encoded_value',
                                                                                        unknown_value=-1),
                                                                         ['person_education'])])),
                                       ('model',
                                        RandomForestClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__class_weight': [None, 'balanced'],
                         'model__max_depth': [None, 10, 20],
                         'model__max_features': ['sqrt'],
                         'model__min_samples_leaf': [1, 2],
                         'model__min_samples_split': [2, 5],
                         'model__n_estimators': [100, 200]},
             verbose=10)

In [20]:
grid_search_cv.best_estimator_ # It will return the best model/estimator

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('OneHotEncoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['person_gender',
                                                   'person_home_ownership',
                                                   'loan_intent',
                                                   'previous_loan_defaults_on_file']),
                                                 ('ordinal',
                                                  OrdinalEncoder(categories=[['High '
                                                                              'School',
                                                                              'Associate',
                                                                              'Bachelor',
                                                                              'Master',
                                                                              'Doctorate']],
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['person_education'])])),
                ('model',
                 RandomForestClassifier(min_samples_leaf=2, min_samples_split=5,
                                        n_estimators=200, random_state=42))])

In [21]:
grid_search_cv.best_params_ # it will return the best parameter values

{'model__class_weight': None,
 'model__max_depth': None,
 'model__max_features': 'sqrt',
 'model__min_samples_leaf': 2,
 'model__min_samples_split': 5,
 'model__n_estimators': 200}

In [22]:
grid_search_cv.cv_results_

{'mean_fit_time': array([1.00435519, 1.93013444, 0.9446444 , 1.89197702, 0.9378171 ,
        1.82833524, 0.93767905, 1.82678308, 0.82203937, 1.68992929,
        0.81388607, 1.62927265, 0.81278162, 1.66344399, 0.79974914,
        1.58554821, 0.99275351, 1.96464615, 0.99104252, 1.88725839,
        0.96988268, 1.85592456, 0.96703668, 1.97072811, 1.0547585 ,
        2.0796494 , 1.00865397, 1.99611382, 1.02479053, 2.102109  ,
        0.98761072, 1.99254174, 0.90154142, 1.78021946, 0.90697703,
        1.66817122, 0.90299306, 1.78271794, 0.86954384, 1.93987131,
        1.18810358, 2.32193918, 1.08438907, 2.14451022, 1.06803436,
        2.28835144, 1.25794945, 1.58876133]),
 'std_fit_time': array([0.03312545, 0.03431983, 0.03441712, 0.04414397, 0.01105089,
        0.02716862, 0.02099577, 0.06396214, 0.03898193, 0.09024607,
        0.02462857, 0.0871224 , 0.04214647, 0.0676712 , 0.0248038 ,
        0.0735881 , 0.05193661, 0.09128992, 0.02768517, 0.09031896,
        0.04364   , 0.12512945, 0.05864417, 0.07413281, 0.08775522,
        0.08440499, 0.03658395, 0.08633702, 0.08037783, 0.12803828,
        0.09444303, 0.15555275, 0.02036784, 0.12471016, 0.04492127,
        0.09881625, 0.06549281, 0.17646633, 0.06703212, 0.16435528,
        0.09903758, 0.16558648, 0.0543784 , 0.08846064, 0.05108297,
        0.17624511, 0.13026271, 0.1838354 ]),
 'mean_score_time': array([0.0529604 , 0.0810514 , 0.04329596, 0.083041  , 0.0491231 ,
        0.07983756, 0.0453023 , 0.07901368, 0.04095101, 0.07552891,
        0.03987803, 0.06872292, 0.03921614, 0.07475295, 0.04125042,
        0.06850224, 0.04751859, 0.08154798, 0.05180364, 0.08060212,
        0.04405174, 0.08204651, 0.05249491, 0.08305473, 0.04957428,
        0.09082947, 0.06937723, 0.08125343, 0.04468818, 0.09294105,
        0.06763515, 0.07857184, 0.0548965 , 0.07952437, 0.04669447,
        0.074156  , 0.04540229, 0.09333401, 0.04430218, 0.08116112,
        0.05473652, 0.09945412, 0.05201497, 0.08715229, 0.05619521,
        0.07985029, 0.04942198, 0.04530683]),
 'std_score_time': array([0.00889199, 0.00333331, 0.00106384, 0.0050627 , 0.00502188,
        0.00604305, 0.00263225, 0.00691788, 0.00324948, 0.01024596,
        0.00153368, 0.00478799, 0.00148735, 0.00883789, 0.0012081 ,
        0.00641701, 0.00318982, 0.00349834, 0.00573938, 0.00387037,
        0.00150054, 0.00638414, 0.01237425, 0.00887436, 0.00350041,
        0.0079515 , 0.02706896, 0.00500126, 0.00087509, 0.01041749,
        0.03107147, 0.00200957, 0.02144818, 0.00778574, 0.00504409,
        0.00309726, 0.00419319, 0.04101326, 0.00376152, 0.00750847,
        0.00537174, 0.00886528, 0.00632251, 0.00427537, 0.01084443,
        0.01124939, 0.00259505, 0.00343089]),
 'param_model__class_weight': masked_array(data=[None, None, None, None, None, None, None, None, None,
                    None, None, None, None, None, None, None, None, None,
                    None, None, None, None, None, None, 'balanced',
                    'balanced', 'balanced', 'balanced', 'balanced',
                    'balanced', 'balanced', 'balanced', 'balanced',
                    'balanced', 'balanced', 'balanced', 'balanced',
                    'balanced', 'balanced', 'balanced', 'balanced',
                    'balanced', 'balanced', 'balanced', 'balanced',
                    'balanced', 'balanced', 'balanced'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_model__max_depth': masked_array(data=[None, None, None, None, None, None, None, None, 10, 10,
                    10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 20, 20, 20,
                    None, None, None, None, None, None, None, None, 10, 10,
                    10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_model__max_features': masked_array(data=['sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt',
                    'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt', 'sqrt'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_model__min_samples_leaf': masked_array(data=[1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1,
                    1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1,
                    2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_model__min_samples_split': masked_array(data=[2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2,
                    5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5,
                    2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_model__n_estimators': masked_array(data=[100, 200, 100, 200, 100, 200, 100, 200, 100, 200, 100,
                    200, 100, 200, 100, 200, 100, 200, 100, 200, 100, 200,
                    100, 200, 100, 200, 100, 200, 100, 200, 100, 200, 100,
                    200, 100, 200, 100, 200, 100, 200, 100, 200, 100, 200,
                    100, 200, 100, 200],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'params': [{'model__class_weight': None,
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__n_estimators': 100},
  {'model__class_weight': None,
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__n_estimators': 200},
  {'model__class_weight': None,
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__n_estimators': 100},
  {'model__class_weight': None,
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__n_estimators': 200},
  {'model__class_weight': None,
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 2,
   'model__n_estimators': 100},
  {'model__class_weight': None,
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 2,
   'model__n_estimators': 200},
  {'model__class_weight': None,
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 5,
   'model__n_estimators': 100},
  {'model__class_weight': None,
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 5,
   'model__n_estimators': 200},
  {'model__class_weight': None,
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__n_estimators': 100},
  {'model__class_weight': None,
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__n_estimators': 200},
  {'model__class_weight': None,
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__n_estimators': 100},
  {'model__class_weight': None,
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__n_estimators': 200},
  {'model__class_weight': None,
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 2,
   'model__n_estimators': 100},
  {'model__class_weight': None,
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 2,
   'model__n_estimators': 200},
  {'model__class_weight': None,
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 5,
   'model__n_estimators': 100},
  {'model__class_weight': None,
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 5,
   'model__n_estimators': 200},
  {'model__class_weight': None,
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__n_estimators': 100},
  {'model__class_weight': None,
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__n_estimators': 200},
  {'model__class_weight': None,
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__n_estimators': 100},
  {'model__class_weight': None,
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__n_estimators': 200},
  {'model__class_weight': None,
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 2,
   'model__n_estimators': 100},
  {'model__class_weight': None,
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 2,
   'model__n_estimators': 200},
  {'model__class_weight': None,
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 5,
   'model__n_estimators': 100},
  {'model__class_weight': None,
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 5,
   'model__n_estimators': 200},
  {'model__class_weight': 'balanced',
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__n_estimators': 100},
  {'model__class_weight': 'balanced',
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__n_estimators': 200},
  {'model__class_weight': 'balanced',
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__n_estimators': 100},
  {'model__class_weight': 'balanced',
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__n_estimators': 200},
  {'model__class_weight': 'balanced',
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 2,
   'model__n_estimators': 100},
  {'model__class_weight': 'balanced',
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 2,
   'model__n_estimators': 200},
  {'model__class_weight': 'balanced',
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 5,
   'model__n_estimators': 100},
  {'model__class_weight': 'balanced',
   'model__max_depth': None,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 5,
   'model__n_estimators': 200},
  {'model__class_weight': 'balanced',
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__n_estimators': 100},
  {'model__class_weight': 'balanced',
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__n_estimators': 200},
  {'model__class_weight': 'balanced',
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__n_estimators': 100},
  {'model__class_weight': 'balanced',
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__n_estimators': 200},
  {'model__class_weight': 'balanced',
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 2,
   'model__n_estimators': 100},
  {'model__class_weight': 'balanced',
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 2,
   'model__n_estimators': 200},
  {'model__class_weight': 'balanced',
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 5,
   'model__n_estimators': 100},
  {'model__class_weight': 'balanced',
   'model__max_depth': 10,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 5,
   'model__n_estimators': 200},
  {'model__class_weight': 'balanced',
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__n_estimators': 100},
  {'model__class_weight': 'balanced',
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 2,
   'model__n_estimators': 200},
  {'model__class_weight': 'balanced',
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__n_estimators': 100},
  {'model__class_weight': 'balanced',
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 1,
   'model__min_samples_split': 5,
   'model__n_estimators': 200},
  {'model__class_weight': 'balanced',
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 2,
   'model__n_estimators': 100},
  {'model__class_weight': 'balanced',
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 2,
   'model__n_estimators': 200},
  {'model__class_weight': 'balanced',
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 5,
   'model__n_estimators': 100},
  {'model__class_weight': 'balanced',
   'model__max_depth': 20,
   'model__max_features': 'sqrt',
   'model__min_samples_leaf': 2,
   'model__min_samples_split': 5,
   'model__n_estimators': 200}],
 'split0_test_score': array([0.91833333, 0.92      , 0.915     , 0.91722222, 0.91833333,
        0.91777778, 0.91777778, 0.92055556, 0.91888889, 0.91777778,
        0.91777778, 0.91722222, 0.915     , 0.91833333, 0.91444444,
        0.915     , 0.91555556, 0.91388889, 0.91777778, 0.91777778,
        0.91666667, 0.915     , 0.91888889, 0.91888889, 0.91611111,
        0.91444444, 0.91666667, 0.91722222, 0.91333333, 0.915     ,
        0.91333333, 0.91277778, 0.88611111, 0.88888889, 0.88222222,
        0.88611111, 0.88277778, 0.88722222, 0.87777778, 0.88444444,
        0.91555556, 0.91722222, 0.92055556, 0.91722222, 0.91666667,
        0.91777778, 0.91555556, 0.91444444]),
 'split1_test_score': array([0.92055556, 0.91944444, 0.92166667, 0.92111111, 0.92      ,
        0.92222222, 0.92388889, 0.92388889, 0.92055556, 0.91888889,
        0.92055556, 0.92      , 0.92277778, 0.91944444, 0.92333333,
        0.92      , 0.92166667, 0.92222222, 0.92333333, 0.92277778,
        0.92055556, 0.92111111, 0.92111111, 0.92111111, 0.92      ,
        0.92166667, 0.915     , 0.91833333, 0.91388889, 0.91777778,
        0.91555556, 0.91555556, 0.88722222, 0.89111111, 0.89      ,
        0.88777778, 0.88333333, 0.88777778, 0.88444444, 0.88833333,
        0.92      , 0.92333333, 0.91444444, 0.91888889, 0.91611111,
        0.91611111, 0.90944444, 0.91444444]),
 'split2_test_score': array([0.92444444, 0.92722222, 0.925     , 0.92722222, 0.92444444,
        0.925     , 0.925     , 0.92333333, 0.92055556, 0.92611111,
        0.92277778, 0.92388889, 0.92111111, 0.92333333, 0.92166667,
        0.92388889, 0.92333333, 0.92444444, 0.92555556, 0.92944444,
        0.92666667, 0.92777778, 0.925     , 0.92944444, 0.92111111,
        0.92277778, 0.91888889, 0.91777778, 0.91944444, 0.91944444,
        0.91333333, 0.91388889, 0.87833333, 0.87888889, 0.87833333,
        0.87722222, 0.87666667, 0.87833333, 0.87777778, 0.87666667,
        0.92444444, 0.92388889, 0.92055556, 0.91944444, 0.91222222,
        0.91944444, 0.90777778, 0.91111111]),
 'split3_test_score': array([0.92722222, 0.92722222, 0.92388889, 0.92777778, 0.925     ,
        0.925     , 0.92388889, 0.925     , 0.92444444, 0.92555556,
        0.92444444, 0.92444444, 0.92888889, 0.92777778, 0.92388889,
        0.92444444, 0.92277778, 0.925     , 0.92833333, 0.925     ,
        0.92166667, 0.925     , 0.92555556, 0.92666667, 0.92277778,
        0.925     , 0.92555556, 0.92722222, 0.92444444, 0.92777778,

In [23]:
results = pd.DataFrame(grid_search_cv.cv_results_)

In [ ]:
# results

In [24]:
results.sort_values(by='rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__class_weight,param_model__max_depth,param_model__max_features,param_model__min_samples_leaf,param_model__min_samples_split,param_model__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
7,1.826783,0.063962,0.079014,0.006918,None,None,sqrt,2,5,200,"{'model__class_weight': None, 'model__max_dept...",0.920556,0.923889,0.923333,0.925000,0.922778,0.923111,0.001474,1
23,1.970728,0.074133,0.083055,0.008874,None,20,sqrt,2,5,200,"{'model__class_weight': None, 'model__max_dept...",0.918889,0.921111,0.929444,0.926667,0.919444,0.923111,0.004196,1
18,0.991043,0.027685,0.051804,0.005739,None,20,sqrt,1,5,100,"{'model__class_weight': None, 'model__max_dept...",0.917778,0.923333,0.925556,0.928333,0.920000,0.923000,0.003778,3
19,1.887258,0.090319,0.080602,0.003870,None,20,sqrt,1,5,200,"{'model__class_weight': None, 'model__max_dept...",0.917778,0.922778,0.929444,0.925000,0.918333,0.922667,0.004338,4
3,1.891977,0.044144,0.083041,0.005063,None,None,sqrt,1,5,200,"{'model__class_weight': None, 'model__max_dept...",0.917222,0.921111,0.927222,0.927778,0.919444,0.922556,0.004225,5
1,1.930134,0.034320,0.081051,0.003333,None,None,sqrt,1,2,200,"{'model__class_weight': None, 'model__max_dept...",0.920000,0.919444,0.927222,0.927222,0.917778,0.922333,0.004058,6
5,1.828335,0.027169,0.079838,0.006043,None,None,sqrt,2,2,200,"{'model__class_weight': None, 'model__max_dept...",0.917778,0.922222,0.925000,0.925000,0.920000,0.922000,0.002824,7
13,1.663444,0.067671,0.074753,0.008838,None,10,sqrt,2,2,200,"{'model__class_weight': None, 'model__max_dept...",0.918333,0.919444,0.923333,0.927778,0.920000,0.921778,0.003432,8
41,2.321939,0.165586,0.099454,0.008865,balanced,20,sqrt,1,2,200,"{'model__class_weight': 'balanced', 'model__ma...",0.917222,0.923333,0.923889,0.926667,0.917778,0.921778,0.003675,8
0,1.004355,0.033125,0.052960,0.008892,None,None,sqrt,1,2,100,"{'model__class_weight': None, 'model__max_dept...",0.918333,0.920556,0.924444,0.927222,0.917778,0.921667,0.003635,10
6,0.937679,0.020996,0.045302,0.002632,None,None,sqrt,2,5,100,"{'model__class_weight': None, 'model__max_dept...",0.917778,0.923889,0.925000,0.923889,0.917778,0.921667,0.003201,11
4,0.937817,0.011051,0.049123,0.005022,None,None,sqrt,2,2,100,"{'model__class_weight': None, 'model__max_dept...",0.918333,0.920000,0.924444,0.925000,0.920000,0.921556,0.002662,12
22,0.967037,0.058644,0.052495,0.012374,None,20,sqrt,2,5,100,"{'model__class_weight': None, 'model__max_dept...",0.918889,0.921111,0.925000,0.925556,0.916667,0.921444,0.003435,13
9,1.689929,0.090246,0.075529,0.010246,None,10,sqrt,1,2,200,"{'model__class_weight': None, 'model__max_dept...",0.917778,0.918889,0.926111,0.925556,0.917778,0.921222,0.003791,14
21,1.855925,0.125129,0.082047,0.006384,None,20,sqrt,2,2,200,"{'model__class_weight': None, 'model__max_dept...",0.915000,0.921111,0.927778,0.925000,0.917222,0.921222,0.004732,14
12,0.812782,0.042146,0.039216,0.001487,None,10,sqrt,2,2,100,"{'model__class_weight': None, 'model__max_dept...",0.915000,0.922778,0.921111,0.928889,0.916667,0.920889,0.004901,16
2,0.944644,0.034417,0.043296,0.001064,None,None,sqrt,1,5,100,"{'model__class_weight': None, 'model__max_dept...",0.915000,0.921667,0.925000,0.923889,0.918889,0.920889,0.003611,16
20,0.969883,0.043640,0.044052,0.001501,None,20,sqrt,2,2,100,"{'model__class_weight': None, 'model__max_dept...",0.916667,0.920556,0.926667,0.921667,0.918889,0.920889,0.003344,18
17,1.964646,0.091290,0.081548,0.003498,None,20,sqrt,1,2,200,"{'model__class_weight': None, 'model__max_dept...",0.913889,0.922222,0.924444,0.925000,0.918889,0.920889,0.004107,18
8,0.822039,0.038982,0.040951,0.003249,None,10,sqrt,1,2,100,"{'model__class_weight': None, 'model__max_dept...",0.918889,0.920556,0.920556,0.924444,0.919444,0.920778,0.001944,20
40,1.188104,0.099038,0.054737,0.005372,balanced,20,sqrt,1,2,100,"{'model__class_weight': 'balanced', 'model__ma...",0.915556,0.920000,0.924444,0.926111,0.917222,0.920667,0.004058,21
11,1.629273,0.087122,0.068723,0.004788,None,10,sqrt,1,5,200,"{'model__class_weight': None, 'model__max_dept...",0.917222,0.920000,0.923889,0.924444,0.916667,0.920444,0.003247,22
10,0.813886,0.024629,0.039878,0.001534,None,10,sqrt,1,5,100,"{'model__class_weight': None, 'model__max_dept...",0.917778,0.920556,0.922778,0.924444,0.916111,0.920333,0.003075,23
16,0.992754,0.051937,0.047519,0.003190,None,20,sqrt,1,2,100,"{'model__class_weight': None, 'model__max_dept...",0.915556,0.921667,0.923333,0.922778,0.918333,0.920333,0.002952,23
27,1.996114,0.086337,0.081253,0.005001,balanced,None,sqrt,1,5,200,"{'model__class_weight': 'balanced', 'model__ma...",0.917222,0.918333,0.917778,0.927222,0.919444,0.920000,0.003685,25
15,1.585548,0.073588,0.068502,0.006417,None,10,sqrt,2,5,200,"{'model__class_weight': None, 'model__max_dept...",0.915000,0.920000,0.923889,0.924444,0.916111,0.919889,0.003871,26
14,0.799749,0.024804,0.041250,0.001208,None,10,sqrt,2,5,100,"{'model__class_weight': None, 'model__max_dept...",0.914444,0.923333,0.921667,0.923889,0.916111,0.919889,0.003871,27
45,2.288351,0.176245,0.079850,0.011249,balanced,20,sqrt,2,2,200,"{'model__class_weight': 'balanced', 'model__ma...",0.917778,0.916111,0.919444,0.925556,0.918889,0.919556,0.003209,28
43,2.144510,0.088461,0.087152,0.004275,balanced,20,sqrt,1,5,200,"{'model__class_weight': 'balanced', 'model__ma...",0.917222,0.918889,0.919444,0.926111,0.915556,0.919444,0.003600,29
25,2.079649,0.084405,0.090829,0.007952,balanced,None,sqrt,1,2,200,"{'model__class_weight': 'balanced', 'model__ma...",0.914444,0.921667,0.922778,0.925000,0.913333,0.919444,0.004675,29
29,2.102109,0.128038,0.092941,0.010417,balanced,None,sqrt,2,2,200,"{'model__class_weight': 'balanced', 'model__ma...",0.915000,0.917778,0.919444,0.927778,0.916667,0.919333,0.004464,31
42,1.084389,0.054378,0.052015,0.006323,balanced,20,sqrt,1,5,100,"{'model__class_weight': 'balanced', 'model__ma...",0.920556,0.914444,0.920556,0.927222,0.912222,0.919000,0.005275,32
24,1.054759,0.087755,0.049574,0.003500,balanced,None,sqrt,1,2,100,"{'model__class_weight': 'balanced', 'model__ma...",0.916111,0.920000,0.921111,0.922778,0.913889,0.918778,0.003285,33
26,1.008654,0.036584,0.069377,0.027069,balanced,None,sqrt,1,5,100,"{'model__class_weight': 'balanced', 'model__ma...",0.916667,0.915000,0.918889,0.925556,0.913333,0.917889,0.004251,34
28,1.024791,0.080378,0.044688,0.000875,balanced,None,sqrt,2,2,100,"{'model__class_weight': 'balanced', 'model__ma...",0.913333,0.913889,0.919444,0.924444,0.915556,0.917333,0.004148,35
47,1.588761,0.183835,0.045307,0.003431,balanced,20,sqrt,2,5,200,"{'model__class_weight': 'balanced', 'model__ma...",0.914444,0.914444,0.911111,0.924444,0.921667,0.917222,0.004994,36
44,1.068034,0.051083,0.056195,0.010844,balanced,20,sqrt,2,2,100,"{'model__class_weight': 'balanced', 'model__ma...",0.916667,0.916111,0.912222,0.925000,0.915556,0.917111,0.004237,37
30,0.987611,0.094443,0.067635,0.031071,balanced,None,sqrt,2,5,100,"{'model__class_weight': 'balanced', 'model__ma...",0.913333,0.915556,0.913333,0.925000,0.917222,0.916889,0.004312,38
31,1.992542,0.155553,0.078572,0.002010,balanced,None,sqrt,2,5,200,"{'model__class_weight': 'balanced', 'model__ma...",0.912778,0.915556,0.913889,0.925000,0.913889,0.916222,0.004478,39
46,1.257949,0.130263,0.049422,0.002595,balanced,20,sqrt,2,5,100,"{'model__class_weight': 'balanced', 'model__ma...",0.915556,0.909444,0.907778,0.923889,0.919444,0.915222,0.006031,40
33,1.780219,0.124710,0.079524,0.007786,balanced,10,sqrt,1,2,200,"{'model__class_weight': 'balanced', 'model__ma...",0.888889,0.891111,0.878889,0.904444,0.893889,0.891444,0.008237,41
32,0.901541,0.020368,0.054896,0.021448,balanced,10,sqrt,1,2,100,"{'model__class_weight': 'balanced', 'model__ma...",0.886111,0.887222,0.878333,0.905000,0.893889,0.890111,0.008933,42
37,1.782718,0.176466,0.093334,0.041013,balanced,10,sqrt,2,2,200,"{'model__class_weight': 'balanced', 'model__ma...",0.887222,0.887778,0.878333,0.903889,0.890000,0.889444,0.008248,43
35,1.668171,0.098816,0.074156,0.003097,balanced,10,sqrt,1,5,200,"{'model__class_weight': 'balanced', 'model__ma...",0.886111,0.887778,0.877222,0.904444,0.888333,0.888778,0.008801,44
39,1.939871,0.164355,0.081161,0.007508,balanced,10,sqrt,2,5,200,"{'model__class_weight': 'balanced', 'model__ma...",0.884444,0.888333,0.876667,0.903889,0.889444,0.888556,0.008879,45
34,0.906977,0.044921,0.046694,0.005044,balanced,10,sqrt,1,5,100,"{'model__class_weight': 'balanced', 'model__ma...",0.882222,0.890000,0.878333,0.899444,0.890000,0.888000,0.007291,46
38,0.869544,0.067032,0.044302,0.003762,balanced,10,sqrt,2,5,100,"{'model__class_weight': 'balanced', 'model__ma...",0.877778,0.884444,0.877778,0.901667,0.891667,0.886667,0.009088,47
36,0.902993,0.065493,0.045402,0.004193,balanced,10,sqrt,2,2,100,"{'model__class_weight': 'balanced', 'model__ma...",0.882778,0.883333,0.876667,0.900556,0.890000,0.886667,0.008127,47

In [25]:
grid_search_cv.predict(xtrain)

array([1, 0, 0, ..., 0, 1, 0], shape=(9000,))